### ISSUE TITLE
请问，有具体的使用例子吗？

### ISSUE THREAD

**Issue by zhanghuid** [paradiseduo/dsdump#1]
比如：
如下 -i 具体指的是什么，要传什么值进去？是 ipa 包还是，ipa 包内的某个目录，有使用例子不？
```bash
dsdump.py -i 
```

小白一枚，或者有相关文档，也麻烦贴一下，谢谢

**Comment by paradiseduo** [comment]
README里面写了啊，这不就是例子吗？
```
> python3 dsdump.py -i ~/Downloads/Payload/xxx.app/xxx -o ~/Desktop/classes
```
你要dump的是machO文件，当然是把machO传进去了

**Comment by zhanghuid** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zhanghuid** [comment]
> 

你好，传入 machO 文件后，导出的是 is.h ，这是什么情况呢？麻烦抽空回答一下，谢谢

```bash
cat is.h 文件后，显示的是：

0x400000000 is mapped to existing memory, exiting
```

**Comment by zhanghuid** [comment]
- 自问自答一下：
可能的原因跟这个有关: [Errors due to mapped memory](https://github.com/DerekSelander/dsdump/issues/30)

- 解决方案
换机器就解决了

**Comment by League2EB** [comment]
> 

糟糕，換不起機器 QaQ

**Comment by paradiseduo** [comment]
> > 
> 
> 糟糕，換不起機器 QaQ

可以用我开发的另一个工具试试
https://github.com/paradiseduo/resymbol

**Comment by League2EB** [comment]
@paradiseduo 想進一步詢問，對於enum裡面的value是可以獲取的嗎?

**Comment by paradiseduo** [comment]
> @paradiseduo 想進一步詢問，對於enum裡面的value是可以獲取的嗎?

还在研究，应该是可以

**Comment by League2EB** [comment]
好的，非常感谢您的研究，我也一直在找寻答案
以下是我想获取的代码全貌

ExampleService.swift里头的 paradiseduo 

对于此研究与答案我觉得并不是免费，若您需要点研究资金，是可以赞助的。

此外，我已经有使用hopper disassembler进行Mach-o的查看，但一无所获

```swift
import Foundation
import Moya

enum ExampleService {
    case fetch()
}

extension ExampleService: TargetType {

    var baseURL: URL {
        return URL(string: https://example.com)!
    }

    var path: String {
        return "/hello/"
    }

    var method: Moya.Method {
        return .get
    }

    var sampleData: Data {
        return Data()
    }

    var task: Task {
        switch self {
        case . fetch():
            var pars = [String: Any]()
            pars["example"] = "paradiseduo"
            return .requestParameters(parameters: pars, encoding: JSONEncoding.default)
        }
    }

    var headers: [String: String]? {
        return [:]
    }
}
```
